### PR TITLE
moved angular install layer, updated installs to handle PyYaml issue

### PR DESCRIPTION
**Pull request by fablet**
Just some minor cleanup and fixing an issue I discovered with the way PyYaml was installing which was breaking the populate-config install.

@morehavoc  Could you review this repo and the Docker hub to make sure we have everything in place to satisfy GreenBuildingRegistry/EnMSCaseStudies#5

### CODE REVIEW

**Comment by morehavoc** [comment]
@fablet good timing! These changes seem fine to me. I am working on publishing these to docker hub this week (gissue #4).

So, I think the main question here is do these changes require a version bump for `EANginxUwsgiBase`  => `ea-base` which will become `earthadvantage/py-base`? I have the 'latest' tag and I have added `V1.0.0` to the current build, which I was planning on tagging as a release in this repo as well. So this could easily be V1.1.0. Then in the other repos you could reference a specific version of the base image. So you would use `earthadvantage/py-base:V1.0.0` for example if you wanted the image before these changes or `earthadvantage/py-base:V1.1.0` if you wanted the version after these changes.

Does that seem reasonable? If you think so, I'll work on connecting up automations too, so that when we merge PRs here they will be pushed to docker hub automatically.

**Comment by fablet** [comment]
@morehavoc 
Two things:
1) To me it would make more sense to label the ea-base `earthadvantage/uwsgi-nginx-base` rather than py-base because the main focal components of that image are getting uwsgi/nginx running more so than the python.

2) Whether this should be `v1.0.0` or `v1.1.0` depends entirely on when you built the repo from main.  I've been meaning to add these changes for a while, because the PyYaml installation broke the operation of `populate-config` a few months ago.  I'm not sure if it was the `ubuntu/nginx:1.18-20.04_edge` or the `node:16` or both but without my changing either of those `FROM` statements, the populate-config script stopped working until I added the `pip3 install --ignore-installed PyYAML` line to `ea-base` and the Angular section of my templates.

**Comment by morehavoc** [comment]
@fablet given that, maybe this should just be a repository of "templates" and we shouldn't used pre-built images. It would mean that you would have to copy some lines from these into dockerfiles when you make them, but would mean that we don't have the overhead of tracking these versions at all. That way each project also has it's own dependencies as well.

**Comment by fablet** [comment]
@morehavoc I'm not sure I'm following what in my last comment is driving the idea of no longer making pre-built images for the `uwsgi-nginx-base`.

**Comment by morehavoc** [comment]
@fablet mostly it's about version control. If these are separate images, we need to keep them up-to-date with their base images so that anytime we pull `:latest` here we know it has the latest of the underlying image. If we just call these templates and copy the lines needed into the project docker file, then it takes care of itself. Each time we build the project docker container it will use the most recent version of the base image with no middle process required.

**Comment by fablet** [comment]
@morehavoc  In that case, can we still make a pre-built image for `EANginxUwsgiBase` following your described versioning above, but would you still please name it `earthadvantage/uwsgi-nginx-base` for clarity.  And I will update any templates that rely on `ea-base` to match

**Comment by morehavoc** [comment]
@fablet I'm suggesting that we don't build pre-built images at all. We just call them "templates" and move those lines into the project docker files.

**Review by morehavoc — APPROVED** [review]

**Pull request merged**
